export const data = [
  {img: '/livros/livro1.jpg', title: 'Educação e Democracia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro2.jpg', title: 'Os segredos da mente milionária', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro3.jpg', title: 'Mentes Únicas', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro4.jpg', title: 'Como eu era antes de você', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro5.jpg', title: 'Biologia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro6.jpg', title: 'Educação e Democracia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro7.jpg', title: 'Educação e Democracia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro8.jpg', title: 'Educação e Democracia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'},
  {img: '/livros/livro9.jpg', title: 'Educação e Democracia', subtitle: 'Como mudar a educação pública numa grande cidade como São Paulo, onde confluem todos os velhos e novos problemas da construção de uma escola para todos em sociedades altamente estratificadas e desiguais?'}
]